version: '3.9'
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    hostname: node-red
    restart: always
    user: root
    ports:
      - 4444:4444
      - 5555:5555
      - 1880:1880
      - 9000:9000
    environment:
      NODE_OPTIONS: --max-old-space-size=3072
      NODE_RED_ENABLE_PROJECTS: False
    volumes:
      - ./data:/data
